name: 'Set Github Variable'
description: 'Greet someone and record the time'
inputs:
    environment-name:
        description:
            'Github environment name. If not provided, will set repository
            variable / secret'
        required: false
        default: null
        type: string
    is-secret:
        description: 'If true, will set secret. If false, will set variable'
        required: false
        default: false
        type: boolean
    name:
        description: 'The name of the varaible / secret'
        required: false
        type: string
    value:
        description: 'The value of the varaible / secret'
        required: true
        type: string
    token:
        description: 'Github token'
        required: true
        type: string

runs:
    using: node20
    main: dist/index.js
