on: [push]

env:
    GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}

jobs:
    test_action:
        runs-on: ubuntu-latest
        name: Test this action
        steps:
            - name: Set Repository Variable
              uses: Estanz0/set-gh-env-vars@v1.1
              with:
                  name: 'Test v1'
                  value: 'Test v1'
                  myToken: ${{ secrets.GH_PAT_TOKEN }}
